# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: docker-compose -f .devcontainer/docker-compose.yml build
  displayName: 'Create docker environment'

container: devcontainer_dev-environment

steps:
- script: ls -lha
  target: devcontainer_dev-environment
# container: devcontainer_dev-environment # TODO connect this container to the compose network devcontainer_default

# - tasks: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     testResultsFiles: '**/TEST-*.xml'
#     goals: 'test'
