# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: setup
  steps:
  - script: docker-compose -f .devcontainer/docker-compose.yml up -d

- job: verify
  steps:
  - script: |
      docker ps
      docker network ls

- job: run_test
  dependsOn: setup
  container: devcontainer_dev-environment
  steps:
  - script: ls -lha
    
# container: devcontainer_dev-environment # TODO connect this container to the compose network devcontainer_default

# - tasks: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     testResultsFiles: '**/TEST-*.xml'
#     goals: 'test'
