# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  SELENIUM_URL: https://www.google.com
  SELENIUM_BROWSER: chrome
  SELENIUM_WAIT: 3
  # SELENIUM_GRID: http://localhost:4444/wd/hub

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      wget https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
      mv OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz $HOME
    displayName: Download JDK16
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '16' 
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: $(HOME)/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
      jdkDestinationDirectory: $(HOME)/externals
      cleanDestinationDirectory: true
  # - bash: docker-compose -f .devcontainer/docker-compose.yml up -d
  #   displayName: Run selenium grid
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      testResultsFiles: '**/TEST-*.xml'
      goals: 'test'
